{% set name = "scikit-plot" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2c7948817fd2dc06879cfe3c1fdde56a8e71fa5ac626ffbe79f043650baa6242

build:
  number: 0
  script: python -m pip install . --no-deps --no-build-isolation -vvv

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - matplotlib-base  >=1.4.0
    - scikit-learn  >=0.18
    - scipy  >=0.9
    - joblib  >=0.10

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - scikitplot
    - scikitplot.plotters
    - scikitplot.helpers
    - scikitplot.classifiers
    - scikitplot.clustering
    - scikitplot.estimators
    - scikitplot.cluster
    - scikitplot.decomposition
    - scikitplot.metrics

about:
  home: https://github.com/reiinakano/scikit-plot/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'An intuitive library to add plotting functionality to scikit-learn objects.'
  description: |
    Scikit-plot is a Python library that provides easy-to-use functions for visualizing 
    machine learning models and evaluation metrics. It is built on top of popular data
    visualization library Matplotlib and works seamlessly with scikit-learn, a widely 
    used machine learning library in Python.
  doc_url: https://scikit-plot.readthedocs.io/en/stable/
  dev_url: https://github.com/reiinakano/scikit-plot

extra:
  recipe-maintainers:
    - ericmjl
    - reiinakano
