travis:
  secure:
    BINSTAR_TOKEN: sKpsRcqezeq9YG1ng+L8RXgLc4ATiLzX+acgvYewwmTPQp12rx+fOtHmaA2IkTH1aVcqUe0MaKb7IOBZLrsDPMOefmD7oesChEryPW6nZGbmYQH1dk3ph22S/AI5Z47jJfhNoupMo+y24rasFr/wtPNBq/jjgdGG0k3QekcNkxd3NWTIvYgwH3/BSpAEn3w3YNR2/g3cB021XUwiPSOxhUNBY391V7qwTXW8HzkK2PsG9R+vE7WpNUK+OdLdnRBUkxsPMGE6O9NMQv3k32JfeIVxZ2JvQPxV57cI1pKtTJjuyUeftLYjmbkhuAjG83dyEDUbiJzqo7V9LUwkYdR8bydu+p7HFauLKYEikGojuDfkYjAgh0ws+Hfukwdife+K/LZKJAg9dEBJ6gF56ATHQ7aMyHI1BAmXBKkfXUy2hHtaaaUFnccD5DVKjrPAnW2kHb0SP0DEM1JBHgaBhpjOjMoIMG5AM/V6TfNVz/eCrODpYa/pIeQdEwhiWPxOEBZizoZB4g934IIrXhc0/MkD5lW4YROZ+/aCrE7/XgED34kaC+j3Vqyrwkx+fqfq5uwWeS4JTnyFqh+Ehv/0K32+7MLK3Sgef8RzqiGxGG2xsdPXWpLYC6rFHILdIitvdwjEmTb/cdhPudM68BbxWIsqpSPVOrewLY+UmTZqWI04UWY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
