travis:
  secure:
    BINSTAR_TOKEN: k7tFqBya1V4d9AtAoR3Aun4bsnb2GxH00Rylx2bqzPVwjFR9I4OCBfWrD2nJ+A6cA4OTieiW642fAbSAc+ORi13IpVrduRA1d+ff+sVBO00bxPVWP25umTgIu13TsPQDbh8i570O/UFhHQMXl+HM8lP/ieGve5vSNvPclBvjhc1hWKhYkj1QVIG2hu22rskfiTd/teMg8fW75NHaDRKt70BxpzalRk6rz5yD3efIyvfHyKwF3/lq4MUSi1BdhNSMMkrZ09yRbNHfPqMyiNJ40xtMR4JyiX1qRGhOzKtKKopYJVZraNrLh0HN4AgBHswMfkkTu9qZfzTEb2OExVjNVvaTwxsXM44VVkC1aYI/CWhkAmieyyghM5fyTq/YlrjM+tYXRjHpDDSfiKinq0tKvyQrXcrh0T3sprCuUn9FEUVLFfuN3i/+lkzfMmc1/w7jTVTuPOWmpb/ILt6KL8HX+rNm6nHRBqL43Vl2V7ssHvYQVo9hdgvaVyvwjquKXhp0ltuUMV0s0+wv9FN9jymDEcwa86ttrK6MvsDDzixVvXfokGnmTFUrO66tNr2daJEXcRXBXjADhNMjq3PCWjCgTpRBryIEuZsW6lP24FMPWn/ho1DYLNM22Yyl3wbsR0m73Auz0W5EZN0IzF7eJHTXolRoBRB9OAracRvUNxPGL2Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
